<?php
/**
 * Currency
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPIWebForm\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * finAPI Web Form 2.0
 *
 * The following pages give you some general information on how to use our APIs.<br/>The actual API services documentation then follows further below. You can use the menu to jump between API sections.<br/><br/>This page has a built-in HTTP(S) client, so you can test the services directly from within this page, by filling in the request parameters and/or body in the respective services, and then hitting the TRY button. Note that you need to be authorized to make a successful API call. To authorize, refer to the '<a target='_blank' href='https://docs.finapi.io/?product=access#tag--Authorization'>Authorization</a>' section of Access, or in case you already have a valid user token, just use the QUICK AUTH on the left.<br/>Please also remember that all user management functions should be looked up in <a target='_blank' href='https://docs.finapi.io/?product=access'>Access</a>.<br/><br/>You should also check out the <a target='_blank' href='https://documentation.finapi.io/webform/'>Web Form 2.0 Public Documentation</a> as well as <a target='_blank' href='https://documentation.finapi.io/access/'>Access Public Documentation</a> for more information. If you need any help with the API, contact <a href='mailto:support@finapi.io'>support@finapi.io</a>.
 *
 * The version of the OpenAPI document: 2.277.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIWebForm\Client\Model;
use \OpenAPIWebForm\Client\ObjectSerializer;

/**
 * Currency Class Doc Comment
 *
 * @category Class
 * @description The ISO-4217 currency code of the amount.&lt;br/&gt;See https://www.iso.org/iso-4217-currency-codes.html for more information.&lt;br/&gt;At the moment, the only possible currency we accept here is:&lt;br/&gt;&amp;bull; for standalone payments - &lt;code&gt;EUR&lt;/code&gt; only;&lt;br/&gt;&amp;bull; for payments with account - the currency associated with the account (word of caution: we support only SEPA payments, hence for non-EUR accounts, payments will be submitted only on best effort basis).
 * @package  OpenAPIWebForm\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Currency
{
    /**
     * Possible values of this enum
     */
    const AED = 'AED';

    const AFN = 'AFN';

    const ALL = 'ALL';

    const AMD = 'AMD';

    const ANG = 'ANG';

    const AOA = 'AOA';

    const ARS = 'ARS';

    const AUD = 'AUD';

    const AWG = 'AWG';

    const AZN = 'AZN';

    const BAM = 'BAM';

    const BBD = 'BBD';

    const BDT = 'BDT';

    const BGN = 'BGN';

    const BHD = 'BHD';

    const BIF = 'BIF';

    const BMD = 'BMD';

    const BND = 'BND';

    const BOB = 'BOB';

    const BOV = 'BOV';

    const BRL = 'BRL';

    const BSD = 'BSD';

    const BTN = 'BTN';

    const BWP = 'BWP';

    const BYN = 'BYN';

    const BZD = 'BZD';

    const CAD = 'CAD';

    const CDF = 'CDF';

    const CHE = 'CHE';

    const CHF = 'CHF';

    const CHN = 'CHN';

    const CHW = 'CHW';

    const CLF = 'CLF';

    const CLP = 'CLP';

    const CNY = 'CNY';

    const COP = 'COP';

    const COU = 'COU';

    const CRC = 'CRC';

    const CUC = 'CUC';

    const CUP = 'CUP';

    const CVE = 'CVE';

    const CZK = 'CZK';

    const DJF = 'DJF';

    const DKK = 'DKK';

    const DOP = 'DOP';

    const DZD = 'DZD';

    const EGP = 'EGP';

    const ERN = 'ERN';

    const ETB = 'ETB';

    const EUR = 'EUR';

    const FJD = 'FJD';

    const FKP = 'FKP';

    const GBP = 'GBP';

    const GEL = 'GEL';

    const GGP = 'GGP';

    const GHS = 'GHS';

    const GIP = 'GIP';

    const GMD = 'GMD';

    const GNF = 'GNF';

    const GTQ = 'GTQ';

    const GYD = 'GYD';

    const HKD = 'HKD';

    const HNL = 'HNL';

    const HRK = 'HRK';

    const HTG = 'HTG';

    const HUF = 'HUF';

    const IDR = 'IDR';

    const ILS = 'ILS';

    const IMP = 'IMP';

    const INR = 'INR';

    const IQD = 'IQD';

    const IRR = 'IRR';

    const ISK = 'ISK';

    const JEP = 'JEP';

    const JMD = 'JMD';

    const JOD = 'JOD';

    const JPY = 'JPY';

    const KES = 'KES';

    const KGS = 'KGS';

    const KHR = 'KHR';

    const KID = 'KID';

    const KMF = 'KMF';

    const KPW = 'KPW';

    const KRW = 'KRW';

    const KWD = 'KWD';

    const KYD = 'KYD';

    const KZT = 'KZT';

    const LAK = 'LAK';

    const LBP = 'LBP';

    const LKR = 'LKR';

    const LRD = 'LRD';

    const LSL = 'LSL';

    const LYD = 'LYD';

    const MAD = 'MAD';

    const MDL = 'MDL';

    const MGA = 'MGA';

    const MKD = 'MKD';

    const MMK = 'MMK';

    const MNT = 'MNT';

    const MOP = 'MOP';

    const MRU = 'MRU';

    const MUR = 'MUR';

    const MVR = 'MVR';

    const MWK = 'MWK';

    const MXN = 'MXN';

    const MXV = 'MXV';

    const MYR = 'MYR';

    const MZN = 'MZN';

    const NAD = 'NAD';

    const NGN = 'NGN';

    const NIO = 'NIO';

    const NIS = 'NIS';

    const NOK = 'NOK';

    const NPR = 'NPR';

    const NTD = 'NTD';

    const NZD = 'NZD';

    const OMR = 'OMR';

    const PAB = 'PAB';

    const PEN = 'PEN';

    const PGK = 'PGK';

    const PHP = 'PHP';

    const PKR = 'PKR';

    const PLN = 'PLN';

    const PRB = 'PRB';

    const PYG = 'PYG';

    const QAR = 'QAR';

    const RMB = 'RMB';

    const RON = 'RON';

    const RSD = 'RSD';

    const RUB = 'RUB';

    const RWF = 'RWF';

    const SAR = 'SAR';

    const SBD = 'SBD';

    const SCR = 'SCR';

    const SDG = 'SDG';

    const SEK = 'SEK';

    const SGD = 'SGD';

    const SHP = 'SHP';

    const SLL = 'SLL';

    const SLS = 'SLS';

    const SOS = 'SOS';

    const SRD = 'SRD';

    const SSP = 'SSP';

    const STN = 'STN';

    const SVC = 'SVC';

    const SYP = 'SYP';

    const SZL = 'SZL';

    const THB = 'THB';

    const TJS = 'TJS';

    const TMT = 'TMT';

    const TND = 'TND';

    const TOP = 'TOP';

    const _TRY = 'TRY';

    const TTD = 'TTD';

    const TVD = 'TVD';

    const TWD = 'TWD';

    const TZS = 'TZS';

    const UAH = 'UAH';

    const UGX = 'UGX';

    const USD = 'USD';

    const USN = 'USN';

    const UYI = 'UYI';

    const UYU = 'UYU';

    const UYW = 'UYW';

    const UZS = 'UZS';

    const VEF = 'VEF';

    const VES = 'VES';

    const VND = 'VND';

    const VUV = 'VUV';

    const WST = 'WST';

    const XAF = 'XAF';

    const XAG = 'XAG';

    const XAU = 'XAU';

    const XBA = 'XBA';

    const XBB = 'XBB';

    const XBC = 'XBC';

    const XBD = 'XBD';

    const XCD = 'XCD';

    const XDR = 'XDR';

    const XOF = 'XOF';

    const XPD = 'XPD';

    const XPF = 'XPF';

    const XPT = 'XPT';

    const XSU = 'XSU';

    const XTS = 'XTS';

    const XUA = 'XUA';

    const XXX = 'XXX';

    const YER = 'YER';

    const ZAR = 'ZAR';

    const ZMW = 'ZMW';

    const ZWB = 'ZWB';

    const ZWL = 'ZWL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AED,
            self::AFN,
            self::ALL,
            self::AMD,
            self::ANG,
            self::AOA,
            self::ARS,
            self::AUD,
            self::AWG,
            self::AZN,
            self::BAM,
            self::BBD,
            self::BDT,
            self::BGN,
            self::BHD,
            self::BIF,
            self::BMD,
            self::BND,
            self::BOB,
            self::BOV,
            self::BRL,
            self::BSD,
            self::BTN,
            self::BWP,
            self::BYN,
            self::BZD,
            self::CAD,
            self::CDF,
            self::CHE,
            self::CHF,
            self::CHN,
            self::CHW,
            self::CLF,
            self::CLP,
            self::CNY,
            self::COP,
            self::COU,
            self::CRC,
            self::CUC,
            self::CUP,
            self::CVE,
            self::CZK,
            self::DJF,
            self::DKK,
            self::DOP,
            self::DZD,
            self::EGP,
            self::ERN,
            self::ETB,
            self::EUR,
            self::FJD,
            self::FKP,
            self::GBP,
            self::GEL,
            self::GGP,
            self::GHS,
            self::GIP,
            self::GMD,
            self::GNF,
            self::GTQ,
            self::GYD,
            self::HKD,
            self::HNL,
            self::HRK,
            self::HTG,
            self::HUF,
            self::IDR,
            self::ILS,
            self::IMP,
            self::INR,
            self::IQD,
            self::IRR,
            self::ISK,
            self::JEP,
            self::JMD,
            self::JOD,
            self::JPY,
            self::KES,
            self::KGS,
            self::KHR,
            self::KID,
            self::KMF,
            self::KPW,
            self::KRW,
            self::KWD,
            self::KYD,
            self::KZT,
            self::LAK,
            self::LBP,
            self::LKR,
            self::LRD,
            self::LSL,
            self::LYD,
            self::MAD,
            self::MDL,
            self::MGA,
            self::MKD,
            self::MMK,
            self::MNT,
            self::MOP,
            self::MRU,
            self::MUR,
            self::MVR,
            self::MWK,
            self::MXN,
            self::MXV,
            self::MYR,
            self::MZN,
            self::NAD,
            self::NGN,
            self::NIO,
            self::NIS,
            self::NOK,
            self::NPR,
            self::NTD,
            self::NZD,
            self::OMR,
            self::PAB,
            self::PEN,
            self::PGK,
            self::PHP,
            self::PKR,
            self::PLN,
            self::PRB,
            self::PYG,
            self::QAR,
            self::RMB,
            self::RON,
            self::RSD,
            self::RUB,
            self::RWF,
            self::SAR,
            self::SBD,
            self::SCR,
            self::SDG,
            self::SEK,
            self::SGD,
            self::SHP,
            self::SLL,
            self::SLS,
            self::SOS,
            self::SRD,
            self::SSP,
            self::STN,
            self::SVC,
            self::SYP,
            self::SZL,
            self::THB,
            self::TJS,
            self::TMT,
            self::TND,
            self::TOP,
            self::_TRY,
            self::TTD,
            self::TVD,
            self::TWD,
            self::TZS,
            self::UAH,
            self::UGX,
            self::USD,
            self::USN,
            self::UYI,
            self::UYU,
            self::UYW,
            self::UZS,
            self::VEF,
            self::VES,
            self::VND,
            self::VUV,
            self::WST,
            self::XAF,
            self::XAG,
            self::XAU,
            self::XBA,
            self::XBB,
            self::XBC,
            self::XBD,
            self::XCD,
            self::XDR,
            self::XOF,
            self::XPD,
            self::XPF,
            self::XPT,
            self::XSU,
            self::XTS,
            self::XUA,
            self::XXX,
            self::YER,
            self::ZAR,
            self::ZMW,
            self::ZWB,
            self::ZWL
        ];
    }
}


