<?php
/**
 * TaskStatus
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPIWebForm\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * finAPI Web Form 2.0
 *
 * The following pages give you some general information on how to use our APIs.<br/>The actual API services documentation then follows further below. You can use the menu to jump between API sections.<br/><br/>This page has a built-in HTTP(S) client, so you can test the services directly from within this page, by filling in the request parameters and/or body in the respective services, and then hitting the TRY button. Note that you need to be authorized to make a successful API call. To authorize, refer to the '<a target='_blank' href='https://docs.finapi.io/?product=access#tag--Authorization'>Authorization</a>' section of Access, or in case you already have a valid user token, just use the QUICK AUTH on the left.<br/>Please also remember that all user management functions should be looked up in <a target='_blank' href='https://docs.finapi.io/?product=access'>Access</a>.<br/><br/>You should also check out the <a target='_blank' href='https://documentation.finapi.io/webform/'>Web Form 2.0 Public Documentation</a> as well as <a target='_blank' href='https://documentation.finapi.io/access/'>Access Public Documentation</a> for more information. If you need any help with the API, contact <a href='mailto:support@finapi.io'>support@finapi.io</a>.
 *
 * The version of the OpenAPI document: 2.277.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPIWebForm\Client\Model;
use \OpenAPIWebForm\Client\ObjectSerializer;

/**
 * TaskStatus Class Doc Comment
 *
 * @category Class
 * @description Status of the task:&lt;br/&gt;&amp;bull; &lt;code&gt;NOT_YET_STARTED&lt;/code&gt; - the task has been enqueued and will be processed soon;&lt;br/&gt;&amp;bull; &lt;code&gt;IN_PROGRESS&lt;/code&gt; - the task has been started and is currently in progress;&lt;br/&gt;&amp;bull; &lt;code&gt;WEB_FORM_REQUIRED&lt;/code&gt; - the task requires a web form to continue the flow with end user involvement;&lt;br/&gt;&amp;bull; &lt;code&gt;COMPLETED&lt;/code&gt; - the task has been successfully completed (final status);&lt;br/&gt;&amp;bull; &lt;code&gt;COMPLETED_WITH_ERROR&lt;/code&gt; - the task has been completed with an error (final status).
 * @package  OpenAPIWebForm\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaskStatus
{
    /**
     * Possible values of this enum
     */
    const NOT_YET_STARTED = 'NOT_YET_STARTED';

    const IN_PROGRESS = 'IN_PROGRESS';

    const WEB_FORM_REQUIRED = 'WEB_FORM_REQUIRED';

    const COMPLETED = 'COMPLETED';

    const COMPLETED_WITH_ERROR = 'COMPLETED_WITH_ERROR';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_YET_STARTED,
            self::IN_PROGRESS,
            self::WEB_FORM_REQUIRED,
            self::COMPLETED,
            self::COMPLETED_WITH_ERROR
        ];
    }
}


